/**
 * Generate one module per react-icons icon we actually use.
 *
 * WHY THIS EXISTS
 *
 * react-icons 5.5.0 has no per-icon entry points: `react-icons/fa` maps to a
 * single 1.37 MB module. Tree-shaking works (1,611 icons drop to the 87 we
 * reference) but a module is indivisible to Rollup, so because the entry chunk
 * needs SOME Fa icons, every retained icon lands in the entry chunk. Measured
 * on this repo that is 48,233 bytes of icons in the homepage bundle, of which
 * the homepage renders 17 worth 9,728 bytes. The other ~38.5 KB is Admin,
 * Portal and Journal iconography riding along on the LCP route.
 *
 * Giving each icon its own module lets Rollup put admin-only icons in the admin
 * chunk, where they belong.
 *
 * WHAT IT DOES
 *
 * Copies each used icon's `GenIcon({...})` body verbatim out of
 * node_modules/react-icons/fa/index.mjs into src/icons/fa/<Name>.ts. The bodies
 * are copied, not re-derived, so the emitted SVG is identical.
 *
 * MAINTENANCE
 *
 * Copied path data does not follow a react-icons upgrade. Run with --check in
 * CI (and after bumping react-icons) to fail if the generated files have
 * drifted from the installed package, the same shape as hero-variants:check.
 *
 *   node scripts/gen-icons.mjs           regenerate
 *   node scripts/gen-icons.mjs --check   verify, non-zero exit on drift
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(root, 'src/icons/fa');
const CHECK = process.argv.includes('--check');

/** Every `FaFoo` referenced anywhere under src/, from the deep or barrel form. */
function collectUsedIcons() {
  const used = new Set();
  const walk = (dir) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) {
        if (e.name === 'icons') continue; // don't scan what we generate
        walk(p);
        continue;
      }
      if (!/\.(tsx?|jsx?)$/.test(e.name)) continue;
      const src = readFileSync(p, 'utf8');
      // Barrel: import { FaX, FaY } from 'react-icons/fa'
      for (const m of src.matchAll(/import\s*\{([^}]*)\}\s*from\s*['"]react-icons\/fa['"]/g)) {
        for (const name of m[1].split(',')) {
          const clean = name.trim().split(/\s+as\s+/)[0].trim();
          if (/^Fa[A-Za-z0-9]+$/.test(clean)) used.add(clean);
        }
      }
      // Deep: import FaX from '.../icons/fa/FaX'
      for (const m of src.matchAll(/from\s*['"][^'"]*icons\/fa\/(Fa[A-Za-z0-9]+)['"]/g)) {
        used.add(m[1]);
      }
    }
  };
  walk(join(root, 'src'));
  return [...used].sort();
}

/**
 * Pull one icon's function body out of the barrel.
 *
 * The generated file is a flat list of `export function FaX (props) { return
 * GenIcon({...})(props); };` so the body is everything between this icon's
 * opening brace and the next `export function`.
 */
function extractBody(barrel, name) {
  const start = barrel.indexOf(`export function ${name} (props) {`);
  if (start === -1) return null;
  const bodyStart = barrel.indexOf('{', start + `export function ${name} (props) `.length);
  const next = barrel.indexOf('\nexport function ', start + 1);
  const chunk = barrel.slice(bodyStart, next === -1 ? barrel.length : next);
  const close = chunk.lastIndexOf('}');
  return chunk.slice(1, close).trim();
}

const barrel = readFileSync(join(root, 'node_modules/react-icons/fa/index.mjs'), 'utf8');
const used = collectUsedIcons();
if (used.length === 0) {
  console.error('gen-icons: found no react-icons/fa usage — refusing to wipe the directory');
  process.exit(1);
}

const files = new Map();
const missing = [];
for (const name of used) {
  const body = extractBody(barrel, name);
  if (!body) { missing.push(name); continue; }
  files.set(
    `${name}.ts`,
    `// GENERATED by scripts/gen-icons.mjs — do not edit.\n` +
      `// Body copied verbatim from react-icons/fa so the SVG is identical.\n` +
      `import { GenIcon, type IconBaseProps } from 'react-icons/lib';\n\n` +
      `export default function ${name}(props: IconBaseProps) {\n  ${body}\n}\n`,
  );
}
if (missing.length) {
  console.error(`gen-icons: not found in react-icons/fa: ${missing.join(', ')}`);
  process.exit(1);
}

if (CHECK) {
  let drifted = 0;
  const onDisk = existsSync(OUT_DIR) ? readdirSync(OUT_DIR) : [];
  for (const extra of onDisk.filter((f) => !files.has(f))) {
    console.error(`gen-icons --check: ${extra} is generated but no longer used`);
    drifted++;
  }
  for (const [file, content] of files) {
    const p = join(OUT_DIR, file);
    if (!existsSync(p) || readFileSync(p, 'utf8') !== content) {
      console.error(`gen-icons --check: ${file} is missing or out of date`);
      drifted++;
    }
  }
  if (drifted) {
    console.error(`\ngen-icons --check: ${drifted} problem(s). Run: node scripts/gen-icons.mjs`);
    process.exit(1);
  }
  console.log(`gen-icons --check: ${files.size} icons up to date.`);
  process.exit(0);
}

if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
mkdirSync(OUT_DIR, { recursive: true });
for (const [file, content] of files) writeFileSync(join(OUT_DIR, file), content);
console.log(`gen-icons: wrote ${files.size} icon modules to src/icons/fa/`);
