import { useState } from 'react';
import { Box, HStack, Text, VStack } from '@chakra-ui/react';
import { FaSyncAlt } from 'react-icons/fa';
import CTAButton from './CTAButton';
import { useAdminLang } from '../../i18n/admin';

/**
 * Triggers a production rebuild so the prerendered static pages catch up with
 * the database.
 *
 * WHY A BUTTON EXISTS AT ALL
 * Prerendering runs at BUILD time. Publishing a photo or a journal post writes
 * to the database, which the live site reads at runtime — but the static HTML
 * that search engines actually read is only regenerated by a deploy. Without
 * this, new content stays invisible to Google until an unrelated deploy happens
 * to occur.
 *
 * ONE COMPONENT, TWO PLACEMENTS
 * The Integrations screen is super-only, and the person publishing journal
 * posts is not a super admin — so a control that lived only there could never
 * be used by the person who needs it. Rather than build the thing twice, this
 * renders compact in the Journal header and as a full card body in Integrations.
 */
const RebuildSiteButton = ({
  adminPassword,
  compact = false,
}: {
  adminPassword: string;
  compact?: boolean;
}) => {
  const { t } = useAdminLang();
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<{ tone: 'ok' | 'bad'; text: string } | null>(null);

  const run = async () => {
    setBusy(true);
    setMsg(null);
    try {
      const res = await fetch('/api/admin/rebuild', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ password: adminPassword }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok && data.success) {
        setMsg({ tone: 'ok', text: t.rebuild.started });
      } else if (res.status === 409 && typeof data.retryInSeconds === 'number') {
        setMsg({ tone: 'bad', text: t.rebuild.cooldown(data.retryInSeconds) });
      } else if (data.needsSetup) {
        setMsg({ tone: 'bad', text: t.rebuild.needsSetup });
      } else {
        setMsg({ tone: 'bad', text: data.error || t.rebuild.failed });
      }
    } catch {
      setMsg({ tone: 'bad', text: t.rebuild.failed });
    } finally {
      setBusy(false);
    }
  };

  const button = (
    <CTAButton
      onClick={run}
      icon={FaSyncAlt}
      variant="outline"
      size="sm"
      isLoading={busy}
      loadingText={t.rebuild.starting}
    >
      <Box as="span" display={{ base: 'none', sm: 'inline' }}>{t.rebuild.action}</Box>
      <Box as="span" display={{ base: 'inline', sm: 'none' }}>{t.rebuild.actionShort}</Box>
    </CTAButton>
  );

  // Compact = button and status side by side on one line. It sits on its own
  // row in AdminJournal, so the status text can simply appear next to the
  // button; an earlier version hid it in a title attribute to avoid reflowing
  // the header, which both hid the message from touch users and did not
  // actually prevent the reflow, because it rendered the text as well.
  if (compact) {
    return (
      <HStack spacing={3} align="center" wrap="wrap">
        {button}
        {msg && (
          <Text
            fontSize="xs"
            color={msg.tone === 'ok' ? 'green.600' : 'red.500'}
            fontWeight="300"
            maxW={{ base: '100%', md: '46ch' }}
          >
            {msg.text}
          </Text>
        )}
      </HStack>
    );
  }

  return (
    <VStack align="flex-start" spacing={3}>
      <Text fontSize="sm" color="gray.500" fontWeight="300" maxW="52ch">
        {t.rebuild.subtitle}
      </Text>
      {button}
      {msg && (
        <Text fontSize="xs" color={msg.tone === 'ok' ? 'green.600' : 'red.500'} fontWeight="300">
          {msg.text}
        </Text>
      )}
    </VStack>
  );
};

export default RebuildSiteButton;
