import { useCallback, useEffect, useState } from 'react';
import { Box, HStack, Text, VStack } from '@chakra-ui/react';
import { FaSyncAlt } from 'react-icons/fa';
import CTAButton from './CTAButton';
import { useAdminLang } from '../../i18n/admin';

/**
 * Publishes pending content to the pages search engines read, by triggering a
 * production rebuild.
 *
 * WHY A BUTTON EXISTS AT ALL
 * Prerendering runs at BUILD time. Publishing a photo or a journal post writes
 * to the database, which the live site reads at runtime — but the static HTML
 * search engines read is only regenerated by a deploy.
 *
 * WHY IT KNOWS WHETHER IT HAS ANYTHING TO DO
 * Each build stamps /build-manifest.json with a fingerprint of the content it
 * baked in. /api/admin/rebuild-status recomputes that fingerprint live and
 * compares. So the button can say "nothing waiting" instead of spending a build
 * to find out — and, more usefully, it shows Vero that a rebuild IS owed after
 * she changes something, which is the only prompt she gets.
 *
 * The disabled state is safe in one direction on purpose: "up to date" can only
 * be reported when a build genuinely captured the current content. A build that
 * never ran, or ran and failed, leaves the deployed manifest stale, so the
 * button stays live rather than locking her out.
 *
 * ONE COMPONENT, TWO PLACEMENTS
 * Integrations is super-only and the person publishing journal posts is not a
 * super admin, so this renders compact on the Journal screen and as a card body
 * in Integrations rather than being built twice.
 */
const RebuildSiteButton = ({
  adminPassword,
  compact = false,
}: {
  adminPassword: string;
  compact?: boolean;
}) => {
  const { t } = useAdminLang();
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<{ tone: 'ok' | 'bad'; text: string } | null>(null);
  // null = still checking.
  const [status, setStatus] = useState<
    { pending: boolean; delta: { photos: number; journal: number } | null } | null
  >(null);

  const loadStatus = useCallback(async () => {
    try {
      const res = await fetch('/api/admin/rebuild-status', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ password: adminPassword }),
      });
      const data = await res.json().catch(() => ({}));
      // An unknown state must never read as "nothing to do" — that would
      // quietly stop her ever rebuilding. Fail toward the button being live.
      setStatus(
        res.ok && data.success
          ? { pending: !!data.pending, delta: data.delta ?? null }
          : { pending: true, delta: null },
      );
    } catch {
      setStatus({ pending: true, delta: null });
    }
  }, [adminPassword]);

  useEffect(() => {
    loadStatus();
  }, [loadStatus]);

  const run = async () => {
    setBusy(true);
    setMsg(null);
    try {
      const res = await fetch('/api/admin/rebuild', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ password: adminPassword }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok && data.success && data.skipped) {
        setMsg({ tone: 'ok', text: t.rebuild.nothingToDo });
        setStatus({ pending: false, delta: null });
      } else if (res.ok && data.success) {
        setMsg({ tone: 'ok', text: t.rebuild.started });
        // Build is running: drain the queue so a second click cannot spend
        // another build before this one lands.
        setStatus({ pending: false, delta: null });
      } else if (res.status === 409 && typeof data.retryInSeconds === 'number') {
        setMsg({ tone: 'bad', text: t.rebuild.cooldown(data.retryInSeconds) });
      } else if (data.needsSetup) {
        setMsg({ tone: 'bad', text: t.rebuild.needsSetup });
      } else {
        setMsg({ tone: 'bad', text: data.error || t.rebuild.failed });
      }
    } catch {
      setMsg({ tone: 'bad', text: t.rebuild.failed });
    } finally {
      setBusy(false);
    }
  };

  const nothingToPublish = status !== null && !status.pending;

  const statusText =
    status === null
      ? t.rebuild.checking
      : !status.pending
        ? t.rebuild.upToDate
        : status.delta && (status.delta.photos !== 0 || status.delta.journal !== 0)
          ? t.rebuild.waiting(status.delta.photos, status.delta.journal)
          : t.rebuild.waitingEdits;

  // An action result replaces the standing status until the next render.
  const line = msg
    ? { text: msg.text, color: msg.tone === 'ok' ? 'green.600' : 'red.500' }
    : { text: statusText, color: status?.pending ? 'brand.accentText' : 'gray.500' };

  const button = (
    <CTAButton
      onClick={run}
      icon={FaSyncAlt}
      variant={nothingToPublish ? 'ghost' : 'outline'}
      size="sm"
      isLoading={busy}
      isDisabled={status === null || nothingToPublish}
      loadingText={t.rebuild.starting}
    >
      <Box as="span" display={{ base: 'none', sm: 'inline' }}>{t.rebuild.action}</Box>
      <Box as="span" display={{ base: 'inline', sm: 'none' }}>{t.rebuild.actionShort}</Box>
    </CTAButton>
  );

  // Compact = button and status side by side. It sits on its own row in
  // AdminJournal, so the text can simply appear beside the button; an earlier
  // version hid it in a title attribute to avoid reflowing the header, which
  // hid it from touch users and did not prevent the reflow anyway.
  if (compact) {
    return (
      <HStack spacing={3} align="center" wrap="wrap">
        {button}
        <Text
          fontSize="xs"
          color={line.color}
          fontWeight="300"
          maxW={{ base: '100%', md: '46ch' }}
        >
          {line.text}
        </Text>
      </HStack>
    );
  }

  return (
    <VStack align="flex-start" spacing={3}>
      <Text fontSize="sm" color="gray.500" fontWeight="300" maxW="52ch">
        {t.rebuild.subtitle}
      </Text>
      {button}
      <Text fontSize="xs" color={line.color} fontWeight="300">
        {line.text}
      </Text>
    </VStack>
  );
};

export default RebuildSiteButton;
